### ISSUE TITLE
Release static manifests (no helm) for v0.6.0-alpha.0+

### ISSUE THREAD

**Issue by aleskandro** [cert-manager/openshift-routes#116]
Hi, after v0.6.0-alpha.0, you deprecated the static manifests in favor of releasing only the helm-based chart. 

The static YAML manifests were very helpful in kustomize-only-based systems. For example, when provisioning a Microshift environment and setting cert-manager and this project's manifests in the manifests.d folder that Microshift applies at start-up time.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
  - https://github.com/cert-manager/openshift-routes/releases/download/v0.6.0-alpha.0/cert-manager-openshift-routes.yaml
```

was enough to deploy the cert-manager with support for openshift routes.

Is it possible to restore the release of the static manifests too?
