### ISSUE TITLE
Can this plugin be used for creating certificate for wildcard route

### ISSUE THREAD

**Issue by soumyajosekol** [cert-manager/openshift-routes#204]
We are using the plugin for ROSA routes with single domain hostnames, and it works perfect.

There is an additional requirement to use the plugin for wildcard routes(sample host: wildcard.example.com). Is there an option to make it working for wildcard routes? Reusing the same annotations/ClusterIssuer is just creating the certificate for domain 'wildcard.example.com' instead of '*.example.com'

ClusterIssuer in reference is already been used to issue wildcard Certificates(Kind: certificate , using dns01 resolver), but we would want to add the option directly in wildcard route

`apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    cert-manager.io/issuer-name: letsencrypt
    cert-manager.io/issuer-kind: ClusterIssuer
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
  name: test-route
spec:
  host: wildcard.example.com
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
    certificate: ''
    key: ''
  to:
    kind: Service
    name: test
    weight: 100
  wildcardPolicy: Subdomain`

``

**Comment by masonwb** [comment]
+1

Ran into this today trying to create the following route
```yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: coder-workspace-route
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-cluster-issuer
    cert-manager.io/alt-names: '*.coder.mydomain.com'
spec:
  host: wildcard.coder.mydomain.com
  to:
    kind: Service
    name: coder
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: Subdomain
```

Which created the following certificate
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-workspace-route-cert
spec:
  dnsNames:
    - 'wildcard.coder.mydomain.com'
    - '*.coder.mydomain.com'
```

Which resulted in the following error:
```
The certificate request has failed to complete and will be retried: Failed to wait for order resource "coder-workspace-route-cert-1-2380212850" to become ready: order is in "errored" state: Failed to create Order: 400 urn:ietf:params:acme:error:malformed: Error creating new order :: Domain name "wildcard.coder.mydomain.com" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.
```

One possible solution would be to loop through any wildcard domains in `dnsNames` after processing the alt names and remove any host from dnsNames that is redundant with the wildcard.
https://github.com/cert-manager/openshift-routes/blob/9d3cf831812bd353d747f480226b04b5f62435b0/internal/controller/sync.go#L313-L326

Let me know if y'all would be interested in a PR with that solution, and if so, what (if anything) I should look out for. Thanks!
